### PR TITLE
Add new airtable forms

### PR DESCRIPTION
**Pull request by mattstratton**
Signed-off-by: Matt Stratton <matt.stratton@hey.com>

### CODE REVIEW

**Comment by mattstratton** [comment]
one thing to consider...should we embed the form instead of linking to it?

**Comment by mattstratton** [comment]
Creating the pages for the forms will require new gatsby templates I suppose, so I think we should go with it this way, and then we can create pages for `/suggest-player` and `/suggest-prompt` and remove the conflicting redirects at that time.

links in other pages are to the redirect so it should work out

**Comment by mattstratton** [comment]
I opened #100 for the additional templates; I think we can merge this without that and pick that up later.

this should not be merged until the airtable forms are confirmed "done" by @mattstratton and @phrawzty

**Comment by phrawzty** [comment]
As of `Mon, 01 Feb 2021 22:47:55 +0100` the forms are 👍 from me.

**Pull request merged**
