### PR TITLE
add new question to FAQ

### PR DESCRIPTION
**Pull request by jerdog**
this should do - short and simple

### CODE REVIEW

**Comment by mattstratton** [comment]
To be clear, we don’t specify the “rating” anywhere. That’s kind of what I meant for the FAQ. Like a question like “is this family friendly?” “While we have a CoC, the show is rated M for Mature” or something.

**Comment by mattstratton** [comment]
It wasn’t about the rating of the games, but the “rating” of the content of the “show”.

**Comment by mattstratton** [comment]
Jackbox games are rated T for Teen anyway 😂

**Comment by jerdog** [comment]
> To be clear, we don’t specify the “rating” anywhere. That’s kind of what I meant for the FAQ. Like a question like “is this family friendly?” “While we have a CoC, the show is rated M for Mature” or something.

Got it... Ok - I adjusted a bit

**Pull request merged**
